version: '3'
services:
  nginx:
    # image: nginx:alpine
    image: fholzer/nginx-brotli
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    read_only: true
    volumes:
      - var-run:/var/run
      - var-cache:/var/cache/nginx
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
      - ./html:/usr/share/nginx/html:ro
      - ${SHARED_CONF}:/etc/nginx/vhost.d:ro
      - ${SHARED_DATA}:${SHARED_DATA}:ro

  dockergen:
    image: nginxproxy/docker-gen
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    environment:
      - SHARED_DATA
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=mail@yourdomain.tld
    volumes_from:
      - nginx
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.traefik.me

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  var-run:
  var-cache: