version: '3'
services:
  nginx:
    # image: nginx:alpine
    image: fholzer/nginx-brotli
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    read_only: true
    volumes:
      - var-run:/var/run
      - var-cache:/var/cache/nginx
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
      - ./html:/usr/share/nginx/html:ro
      - ${SHARED_CONF}:/etc/nginx/vhost.d:ro
      - ${SHARED_DATA}:${SHARED_DATA}:ro

  dockergen:
    image: nginxproxy/docker-gen
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    environment:
      - SHARED_DATA
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d:rw
      - ${SHARED_CONF}:/etc/nginx/vhost.d:ro
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

volumes:
  # conf:
  # vhost:
  # html:
  # certs:
  acme:
  var-run:
  var-cache: