#!/bin/bash

# --- Base Environment Variables

SCRIPTS=$(realpath $(dirname "$0"))
THIS=$SCRIPTS/$(basename "$0")
ROOT=$(realpath $SCRIPTS/..)
CERTS=$ROOT/certs

cd $ROOT

source $SCRIPTS/lib/custom-commands

handle-custom-commands "$@"

# in some cases (like global help) we just want to stop the execution immediately
[ $STOP ] && exit 0
