#!/bin/bash

# ------------------------------------------------------------------
# This script wraps docker-compose to provide environment based
# defaults and added functionality.
#
# Use it from the project root just like docker-composer
#
# example:
#
# scripts/dev up
# ------------------------------------------------------------------

# take a look to this file to learn more on the predefined
# environment variables and functions
source $(dirname "$0")/lib/init

source update-certificates --check

COMMON="-f docker-compose.yml"

docker-compose $COMMON "$@"
